apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: mtjacr001/.azurecr.io//azure-vote-front
    newTag: df65fe11673a7f5c3c6ee88737a3257d7ffddc47
  - name: mtjacr001/.azurecr.io//azure-vote-back
    newTag: df65fe11673a7f5c3c6ee88737a3257d7ffddc47
resources:
  - manifests.yaml