apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: mtjacr001/.azurecr.io//azure-vote-front
    newTag: 15aec2f6606a946870de022d4809f2866b7eb6e4
  - name: mtjacr001/.azurecr.io//azure-vote-back
    newTag: 15aec2f6606a946870de022d4809f2866b7eb6e4
resources:
  - manifests.yaml