apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: mtjacr001/.azurecr.io//azure-vote-front
    newTag: 9a72e9e7c56d5b0c1f26a80b20cdfb439171686b
  - name: mtjacr001/.azurecr.io//azure-vote-back
    newTag: 9a72e9e7c56d5b0c1f26a80b20cdfb439171686b
resources:
  - manifests.yaml