apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: mtjacr001/.azurecr.io//azure-vote-front
    newTag: 095374bee5fe03287512c8710de57cd46c568035
  - name: mtjacr001/.azurecr.io//azure-vote-back
    newTag: 095374bee5fe03287512c8710de57cd46c568035
resources:
  - manifests.yaml